#!/bin/env python3

import click
import conffwk

@click.command()
@click.option('--dac', '-d', type=int, default=15,
              help="DAC value for pulsers (0-63)")
@click.option('--baseline', '-b', type=int, default=2,
              help="Baseline for all channels (0: high, 1: low, 2: mixed)")
@click.option('--gain_match', '-g', type=bool, default=True,
              help="Gain matching for pulser response")
@click.option('--gain', '-g', type=int, default=2,
              help="Gain for all channels (0-3: 14, 25, 7.8, 4.7 mV/fC)")
@click.option('--peak_time', '-p', type=int, default=3,
              help="Shaping time for all channels (0-3: 1, 0.5, 3, 2 us)")
@click.argument('oks_session_file', type=click.Path(exists=True, dir_okay=False, writable=True)) # Usually defaults/wiecconfs.data.xml
def update_settings(oks_session_file, dac, baseline, gain_match, gain, peak_time):
    db = conffwk.Configuration("oksconflibs:"+oks_session_file)

    femb = db.get_dals("FEMBSettings")
    femb[0].pulse_dac = dac
    femb[0].baseline = baseline
    femb[0].gain_match = gain_match
    femb[0].gain = gain
    femb[0].peak_time = peak_time
    db.update_dal(femb[0])

    db.commit()

if __name__ == '__main__':
  update_settings()
